." Process this file with
." groff -man -Tascii jellyfin.1
."
.TH jellyfin

.Sh NAME
.B jellyfin
- CLI companion tool for the Jellyfin amd64.tar.gz package

.SH VERSION
.B Jellyfin - The CLI Tool - v1.4.6

.SH SYNOPSIS
.B jellyfin

.SH DESCRIPTION
.B jellyfin
is a set of scripts to install and update the jellyfin-combined tar.gz

.SH USAGE
.B SYNTAX
- jellyfin -[COMMAND] [PARAMETER]
.TP
.SS COMMANDS
.TP
.B -b     [DIRECTORY] Input directory to output backup archive.
.TP
.B -d     Disable Jellyfin on System Start.
.TP
.B -e     Enable Jellyfin on System Start.
.TP
.B -h     Print this Help.
.TP
.B -i     [FILE.tar] Input file to Import jellyfin-backup.tar.
.TP
.B -p     Reset the permissions of Jellyfin's Media Library.
.TP
.B -r     Restart Jellyfin.
.TP
.B -s     Start Jellyfin.
.TP
.B -S     Stop Jellyfin.
.TP
.B -t     Status of Jellyfin.
.TP
.B -u     [URL - optional] Downloads and updates the current stable or supplied Jellyfin version.
.TP
.B -U     Update Jellyfin - The CLI Tool.
.TP
.B -ub    Update Jellyfin to the most recent Beta.
.TP
.B -v     Get the current installed version of Jellyfin.
.TP
.B -vs    Switch Jellyfin version for another previously installed version.
.TP
.B -rv    Remove a Jellyfin version.
.TP
.B -rc    Removes old https certifications and creates new ones for the next 365 days.
.TP
.B -rn    Batch renaming script for TV shows.
.TP
.B -ls    Tell Jellyfin to scan your media library.
.TP
.B -cp    Change Jellyfins http network port - Default = 8096.
.TP
.B -cps   Change Jellyfins https network port - Default = 8920.
.TP
.B -ik    Import an API key.
.TP
.B -X     Uninstall Jellyfin Completely.

.SH EXAMPLE
.TP
.B To stop jellyfin, disable on startup, backup, and then start the jellyfin server:
.TP
.B 'sudo jellyfin -S -d -b /home/$USER/ -s'

.SH FILES
.TP
.I
/opt/jellyfin
.TP
.I
/etc/jellyfin.conf
.TP
.I
/bin/jellyfin

.SH URL TO NEW VERSIONS
.PP
***WARNING*** ONLY USE COMBINED(Web & Server) PACKAGES
https://repo.jellyfin.org/releases/server/linux/versions/

.SH COPYRIGHT
.PP
Copyright 2021 Smiley McSmiles. All rights reserved
https://www.github.com/Smiley-McSmiles/jellyfin-cli

.SH CREDITS
.PP
Jellyfin-cli and this man page was created by Smiley McSmiles <SmileyMcSmiles@Proton.me>

